# Generated by Django 4.0.4 on 2022-06-06 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendees', '0006_lounge_aforo_lounge_aforo_current'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('lounge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendees.lounge')),
            ],
        ),
    ]
