# Generated by Django 4.0.4 on 2022-06-11 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operator',
            name='lounge',
        ),
    ]
