# Generated by Django 4.0.4 on 2022-06-05 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('total_hours', models.IntegerField()),
                ('shares_account', models.CharField(choices=[('TS', 'Tickets'), ('DP', 'Departures'), ('TD', 'Tickets and Departures')], default='TD', max_length=300)),
                ('notice_consecutive_entries', models.BooleanField(default=True)),
                ('notice_consecutive_departures', models.BooleanField(default=True)),
                ('count_hours', models.BooleanField(default=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('attendees_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendees.attendeesgroup')),
            ],
        ),
    ]
