# Generated by Django 4.0.4 on 2022-06-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='aforo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
