# Generated by Django 4.0.4 on 2022-06-10 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0001_initial'),
        ('events', '0004_alter_event_count_trade_show_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='operators',
            field=models.ManyToManyField(blank=True, to='operators.operator'),
        ),
    ]
