# Generated by Django 4.0.4 on 2022-06-05 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendeesGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Lounge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('attendees_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendees.attendeesgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('hours', models.IntegerField()),
                ('entrie', models.BooleanField(default=False)),
                ('output', models.BooleanField(default=False)),
                ('attendees_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendees.attendeesgroup')),
                ('lounge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendees.lounge')),
            ],
        ),
    ]
