# Generated by Django 4.0.4 on 2022-06-05 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendeesgroup',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='attendees_list'),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='lounge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendees.lounge'),
        ),
    ]
