# Generated by Django 4.0.4 on 2022-06-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0003_alter_attendeesgroup_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='id_qr',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
