# Generated by Django 4.0.4 on 2022-06-06 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0004_attendee_id_qr_alter_attendee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='attendees_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendees.attendeesgroup'),
        ),
    ]
