# Generated by Django 4.0.4 on 2022-06-06 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0005_alter_attendee_attendees_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='lounge',
            name='aforo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lounge',
            name='aforo_current',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
