# Generated by Django 4.0.4 on 2022-06-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0007_attendee_entrie_datetime_attendee_output_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='hours',
            field=models.DecimalField(decimal_places=20, default=0, max_digits=20),
        ),
    ]
