# Generated by Django 4.0.4 on 2022-06-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0008_alter_attendee_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='hours',
            field=models.FloatField(default=0),
        ),
    ]
