# Generated by Django 4.0.4 on 2022-06-07 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0009_alter_attendee_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='hours',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
