# Generated by Django 4.0.4 on 2022-06-07 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0012_remove_attendee_attendees_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='lounge',
        ),
        migrations.AddField(
            model_name='attendeesgroup',
            name='attendees',
            field=models.ManyToManyField(to='attendees.attendee'),
        ),
    ]
