# Generated by Django 4.0.4 on 2022-06-07 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0013_remove_attendee_lounge_attendeesgroup_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='lounge',
            name='attendees',
            field=models.ManyToManyField(to='attendees.attendee'),
        ),
    ]
