# Generated by Django 4.0.4 on 2022-06-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0014_lounge_attendees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lounge',
            name='attendees_group',
        ),
        migrations.AddField(
            model_name='attendeesgroup',
            name='lounge',
            field=models.ManyToManyField(to='attendees.lounge'),
        ),
        migrations.AlterField(
            model_name='attendeesgroup',
            name='attendees',
            field=models.ManyToManyField(blank=True, to='attendees.attendee'),
        ),
    ]
