# Generated by Django 4.0.4 on 2022-06-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0015_remove_lounge_attendees_group_attendeesgroup_lounge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendeesgroup',
            name='lounge',
        ),
        migrations.AddField(
            model_name='attendeesgroup',
            name='lounges',
            field=models.ManyToManyField(blank=True, to='attendees.lounge'),
        ),
    ]
