# Generated by Django 4.0.4 on 2022-06-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0016_remove_attendeesgroup_lounge_attendeesgroup_lounges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lounge',
            name='attendees',
            field=models.ManyToManyField(blank=True, to='attendees.attendee'),
        ),
    ]
