# Generated by Django 4.0.4 on 2022-06-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0017_alter_lounge_attendees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='output',
            field=models.BooleanField(default=True),
        ),
    ]
