# Generated by Django 4.0.4 on 2022-06-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0018_alter_attendee_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lounge',
            name='aforo_current',
            field=models.IntegerField(default=0),
        ),
    ]
