# Generated by Django 4.0.4 on 2022-06-10 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0019_alter_lounge_aforo_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lounge',
            name='aforo_current',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
