# Generated by Django 4.0.4 on 2022-06-11 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0002_remove_operator_lounge'),
        ('attendees', '0020_alter_lounge_aforo_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='lounge',
            name='operators',
            field=models.ManyToManyField(to='operators.operator'),
        ),
    ]
