# Generated by Django 4.0.4 on 2022-06-12 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operators', '0002_remove_operator_lounge'),
        ('attendees', '0021_lounge_operators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lounge',
            name='operators',
            field=models.ManyToManyField(blank=True, to='operators.operator'),
        ),
    ]
