# Generated by Django 4.0.4 on 2022-06-12 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0023_lounge_attendees_inside_lounge_attendees_outside'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lounge',
            name='attendees_inside',
        ),
        migrations.RemoveField(
            model_name='lounge',
            name='attendees_outside',
        ),
        migrations.AddField(
            model_name='lounge',
            name='afoto_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
