# Generated by Django 4.0.4 on 2022-06-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0026_attendee_hour_attendee_minut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='minut',
        ),
        migrations.AlterField(
            model_name='attendee',
            name='hours',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
