# Generated by Django 4.0.4 on 2022-06-20 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0028_lounge_outputs_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lounge',
            name='outputs_total',
        ),
    ]
