# Generated by Django 4.0.4 on 2022-06-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0029_remove_lounge_outputs_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='output',
            field=models.BooleanField(default=False),
        ),
    ]
