# Generated by Django 4.0.4 on 2022-06-28 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0030_alter_attendee_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='output',
            field=models.BooleanField(default=True),
        ),
    ]
